language: ruby
script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
gemfile:
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
matrix:
  allow_failures:
    - rvm: ruby-head